import 'dotenv/config';
import express from 'express';
import multer from 'multer';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express(); const PORT=process.env.PORT||3000;
const publicDir=path.join(__dirname,'public'); const previewDir=path.join(publicDir,'previews'); const privateDir=path.join(__dirname,'storage','private'); const dbPath=path.join(__dirname,'data','products.json');
for(const d of [previewDir,privateDir,path.dirname(dbPath)]) fs.mkdirSync(d,{recursive:true});
const tempDir=path.join(__dirname,'storage','tmp');fs.mkdirSync(tempDir,{recursive:true});
const upload=multer({dest:tempDir,limits:{fileSize:1024*1024*1024}});
app.use(express.json()); app.use(express.static(publicDir));
const tokens=new Map(); const orderProducts=new Map();
function readProducts(){try{return JSON.parse(fs.readFileSync(dbPath,'utf8'))}catch{return[]}}
function writeProducts(p){fs.writeFileSync(dbPath,JSON.stringify(p,null,2))}
function safeExt(name){return path.extname(name).toLowerCase().replace(/[^.a-z0-9]/g,'').slice(0,8)}
function slugify(s){return s.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||crypto.randomUUID().slice(0,8)}
function paypalBase(){return process.env.PAYPAL_ENV==='live'?'https://api-m.paypal.com':'https://api-m.sandbox.paypal.com'}
async function paypalToken(){const id=process.env.PAYPAL_CLIENT_ID,secret=process.env.PAYPAL_CLIENT_SECRET;if(!id||!secret||id.startsWith('YOUR_'))throw new Error('PayPal credentials are not configured');const auth=Buffer.from(`${id}:${secret}`).toString('base64');const r=await fetch(`${paypalBase()}/v1/oauth2/token`,{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});const d=await r.json();if(!r.ok)throw new Error(d.error_description||'PayPal authentication failed');return d.access_token;}
async function paypal(url,opts={}){const token=await paypalToken();const r=await fetch(`${paypalBase()}${url}`,{...opts,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','PayPal-Request-Id':crypto.randomUUID(),...(opts.headers||{})}});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={raw:text}}if(!r.ok)throw new Error(data.message||data.details?.[0]?.description||`PayPal HTTP ${r.status}`);return data;}
app.get('/api/config',(req,res)=>res.json({paypalClientId:process.env.PAYPAL_CLIENT_ID||'NOT_CONFIGURED',paypalSdkUrl:process.env.PAYPAL_ENV==='live'?'https://www.paypal.com/web-sdk/v6/core':'https://www.sandbox.paypal.com/web-sdk/v6/core',storeName:process.env.STORE_NAME||'MotionVault 4K'}));
app.get('/api/products',(req,res)=>res.json(readProducts().map(({file,...p})=>p)));
app.post('/api/orders',async(req,res)=>{try{const p=readProducts().find(x=>x.id===req.body.productId);if(!p)return res.status(404).json({error:'Product not found'});const order=await paypal('/v2/checkout/orders',{method:'POST',body:JSON.stringify({intent:'CAPTURE',purchase_units:[{reference_id:p.id,description:p.title,amount:{currency_code:'USD',value:Number(p.price).toFixed(2)}}]})});orderProducts.set(order.id,p.id);res.json({id:order.id});}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/orders/:orderId/capture',async(req,res)=>{try{const expectedProduct=orderProducts.get(req.params.orderId);if(!expectedProduct||expectedProduct!==req.body.productId)return res.status(400).json({error:'Order/product mismatch'});const p=readProducts().find(x=>x.id===expectedProduct);if(!p)return res.status(404).json({error:'Product not found'});const order=await paypal(`/v2/checkout/orders/${encodeURIComponent(req.params.orderId)}/capture`,{method:'POST',body:'{}'});if(order.status!=='COMPLETED')return res.status(400).json({error:`Payment status is ${order.status}`});const paid=order.purchase_units?.[0]?.payments?.captures?.[0];if(!paid||paid.status!=='COMPLETED'||paid.amount?.currency_code!=='USD'||Number(paid.amount?.value)!==Number(Number(p.price).toFixed(2)))return res.status(400).json({error:'Captured amount could not be verified'});const token=crypto.randomBytes(32).toString('hex');tokens.set(token,{productId:p.id,expires:Date.now()+24*60*60*1000});orderProducts.delete(req.params.orderId);res.json({orderId:order.id,captureId:paid.id,downloadUrl:`/download/${token}`});}catch(e){res.status(500).json({error:e.message})}});
app.get('/download/:token',(req,res)=>{const t=tokens.get(req.params.token);if(!t||t.expires<Date.now()){tokens.delete(req.params.token);return res.status(410).send('This download link has expired.');}const p=readProducts().find(x=>x.id===t.productId);if(!p)return res.status(404).send('Product not found.');const file=path.join(privateDir,path.basename(p.file));if(!fs.existsSync(file))return res.status(404).send('File not found.');res.download(file,`${slugify(p.title)}${path.extname(file)}`);});
app.post('/api/admin/products',upload.fields([{name:'preview',maxCount:1},{name:'wallpaper',maxCount:1}]),(req,res)=>{const cleanup=()=>Object.values(req.files||{}).flat().forEach(f=>{if(fs.existsSync(f.path))fs.unlinkSync(f.path)});try{if(!process.env.ADMIN_KEY||req.body.adminKey!==process.env.ADMIN_KEY){cleanup();return res.status(401).json({error:'Invalid admin key'});}const preview=req.files?.preview?.[0],wallpaper=req.files?.wallpaper?.[0];if(!preview||!wallpaper){cleanup();return res.status(400).json({error:'Preview and wallpaper files are required'});}const products=readProducts();let id=slugify(req.body.title);if(products.some(p=>p.id===id))id+=`-${Date.now().toString(36)}`;const previewName=`${id}-${crypto.randomBytes(4).toString('hex')}${safeExt(preview.originalname)}`;const fileName=`${id}-${crypto.randomBytes(4).toString('hex')}${safeExt(wallpaper.originalname)}`;fs.renameSync(preview.path,path.join(previewDir,previewName));fs.renameSync(wallpaper.path,path.join(privateDir,fileName));const product={id,title:String(req.body.title).trim(),description:String(req.body.description).trim(),price:Number(req.body.price).toFixed(2),type:req.body.type==='static'?'static':'animated',resolution:String(req.body.resolution||'4K').trim(),preview:`/previews/${previewName}`,file:fileName,featured:false};if(!product.title||!product.description||Number(product.price)<0.5)throw new Error('Invalid product data');products.unshift(product);writeProducts(products);res.json({ok:true,product:{...product,file:undefined}});}catch(e){cleanup();res.status(400).json({error:e.message})}});
app.listen(PORT,()=>console.log(`MotionVault 4K running at http://localhost:${PORT}`));
